; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes='loop(loop-reduce)' %s | FileCheck %s
; REQUIRES: asserts

; Test that LoopStrengthReduce maintains LCSSA form for parent loops when
; transforming nested loops with multiple children. The parent loop's LCSSA
; form must be preserved after transformations to its child loops.

target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

; Verify that LCSSA PHI nodes are correctly inserted for values crossing loop boundaries.
; CHECK-LABEL: @nested_loops_lcssa_preservation(
; CHECK:       outer_loop.loopexit:
; CHECK-NEXT:    %inner_1_counter.lcssa = phi i64 [ %lsr.iv.next, %inner_1 ]
; CHECK-NEXT:    br label %outer_loop
; CHECK:       outer_loop:
; CHECK-NEXT:    %outer_counter = phi i64 [ 0, %entry ], [ %inner_1_counter.lcssa, %outer_loop.loopexit ]
; CHECK:       inner_1.preheader:
; CHECK-NEXT:    %inner_0_counter.lcssa{{.*}} = phi i64 [ %inner_0_counter, %inner_0 ]

define amdgpu_kernel void @nested_loops_lcssa_preservation(i1 %inner_0_cmp, i1 %inner_1_cmp) {
entry:
  br label %outer_loop

outer_loop:                                       ; preds = %inner_1, %entry
  %outer_counter = phi i64 [ 0, %entry ], [ %inner_1_counter, %inner_1 ]
  br label %inner_0

inner_0:                                          ; preds = %inner_0, %outer_loop
  %inner_0_counter = phi i64 [ %outer_counter, %outer_loop ], [ 0, %inner_0 ]
  br i1 %inner_0_cmp, label %inner_0, label %inner_1

inner_1:                                          ; preds = %inner_1, %inner_0
  %inner_1_counter = phi i64 [ %inner_1_counter_next, %inner_1 ], [ %inner_0_counter, %inner_0 ]
  %inner_1_counter_next = add i64 %inner_1_counter, 1
  br i1 %inner_1_cmp, label %inner_1, label %outer_loop
}

